import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import ConfettiProvider from "@/components/Providers/ConfettiProvider";
import { ThemeProvider } from "@/components/Providers/ThemeProvidder";
import ToasterPrivder from "@/components/Providers/ToasterPrivder";
import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/components/Providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "TSI Learning Center",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfettiProvider />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <SessionProvider>{children}</SessionProvider>
          </QueryProvider>
          <ToasterPrivder />
        </ThemeProvider>
      </body>
    </html>
  );
};

export { metadata };
export default Layout;
