import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";
import ConfettiProvider from "@/components/Providers/ConfettiProvider";
import { ThemeProvider } from "@/components/Providers/ThemeProvidder";
import ToasterPrivder from "@/components/Providers/ToasterPrivder";
import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/components/Providers/QueryProvider";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Learning Center",
  description: "Generated by create next app",
};

type LayoutProps = Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>;

const Layout = async ({ children, params }: LayoutProps) => {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfettiProvider />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <SessionProvider>
              <NextIntlClientProvider locale={locale}>
                {children}
              </NextIntlClientProvider>
            </SessionProvider>
          </QueryProvider>
          <ToasterPrivder />
        </ThemeProvider>
      </body>
    </html>
  );
};

export { metadata };
export default Layout;
